import type * as protobufType from 'protobufjs/minimal';
/**
 * IMPORTANT NOTE: This file is replaced by code generated by `compilemessages.js` script after build process.
 * IMPORTANT NOTE: This file is replaced by code generated by `compilemessages.js` script after build process.
 * IMPORTANT NOTE: This file is replaced by code generated by `compilemessages.js` script after build process.
 * IMPORTANT NOTE: This file is replaced by code generated by `compilemessages.js` script after build process.
 */
declare const _default: Record<string, protobufType.Type>;
export default _default;
